version: '3.7'
services:
  mongo:
    image: mongo
    container_name: sylvanlibrary_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: sylvanlibrary_mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  redis:
    image: redis
    container_name: sylvanlibrary_redis
    command: [ "redis-server", "--bind", "0.0.0.0" ]
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight
    container_name: sylvanlibrary_redisinsight
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_db:/db
    depends_on:
      - redis
volumes:
  redisinsight_db: